site_name: Alphavantage Java
repo_name: crazzyghost/alphavantage-java
repo_url: https://github.com/crazzyghost/alphavantage-java
site_description: "Fluent Java wrapper for Alphavantage API"
site_author: S. M. Sefa-Yeboah

copyright: 'Copyright &copy; 2026 S. M. Sefa-Yeboah'

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: octicons/sun-24
        name: "Switch to Dark Mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: octicons/moon-24
        name: "Switch to Light Mode"
  features:
    - navigation.instant
    - navigation.indexes

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes

nav:
  - Overview: index.md
  - API: api/index.html
  - Recipes:
      - Stock Time Series: timeseries.md
      - Forex (FX): forex.md
      - Crypto Currencies: crypto.md
      - Exchange Rates: exchangerate.md
      - Technical Indicators: technicalindicator.md
      - Technical Indicators (Legacy): indicators.md
      - Sector Performances: sector.md
      - Fundamental Data: fundamentaldata.md
      - Economic Indicators: economicindicator.md
      - Global Market Status: marketstatus.md
      - Ticker/Symbol Search: search.md
  - Changelog: changelog.md
