package com.crazzyghost.alphavantage.parameters;

public enum Function {
    //Stock Time Series Functions
    TIME_SERIES_INTRADAY,
    TIME_SERIES_DAILY,
    TIME_SERIES_DAILY_ADJUSTED,
    TIME_SERIES_WEEKLY,
    TIME_SERIES_WEEKLY_ADJUSTED,
    TIME_SERIES_MONTHLY,
    TIME_SERIES_MONTHLY_ADJUSTED,
    //Exchange Rate
    CURRENCY_EXCHANGE_RATE,
    //Forex (FX) Functions
    FX_INTRADAY,
    FX_DAILY,
    FX_WEEKLY,
    FX_MONTHLY,
    //Digital Currency Functions
    DIGITAL_CURRENCY_DAILY,
    DIGITAL_CURRENCY_WEEKLY,
    DIGITAL_CURRENCY_MONTHLY,
    //Technical Indications
    SMA,
    EMA,
    WMA,
    DEMA,
    TEMA,
    TRIMA,
    KAMA,
    MAMA,
    VWAP,
    T3,
    MACD,
    MACDEXT,
    STOCH,
    STOCHF,
    RSI,
    STOCHRSI,
    WILLR,
    ADX,
    ADXR,
    APO,
    PPO,
    MOM,
    BOP,
    CCI,
    CMO,
    ROC,
    ROCR,
    AROON,
    AROONOSC,
    MFI,
    TRIX,
    ULTOSC,
    DX,
    MINUS_DI,
    PLUS_DI,
    MINUS_DM,
    PLUS_DM,
    BBANDS,
    MIDPOINT,
    MIDPRICE,
    SAR,
    TRANGE,
    ATR,
    NATR,
    AD,
    ADOSC,
    OBV,
    HT_TRENDLINE,
    HT_SINE,
    HT_TRENDMODE,
    HT_DCPERIOD,
    HT_DCPHASE,
    HT_PHASOR
}
